#!/usr/bin/env python3
"""Canonical Dispatch feature/user-story matrix.

This module is the single source of truth for the Dispatch QA matrix. Each row
is one discrete, testable user-facing behavior derived from the code. Running
this script renders ``feature-user-stories.csv`` next to it.

Columns:
  id              - stable identifier (AREA-NN)
  area            - feature area
  feature         - short feature name
  user_story      - "As a <role>, I want <goal> so that <benefit>"
  expected        - precise, observable expected behavior
  source_refs     - file:symbol / file:line backing the behavior
  status          - Documented | Tested | Fixed | Verified
  test_method     - how the story was exercised (pytest node, pilot, manual)
  test_result     - PASS | FAIL | N/A (+ short note) from the FIRST test pass
  errors_found    - logistical/UX errors discovered during testing
  fix_applied     - fix made in Phase 3 (commit-level summary)
  retest_result   - PASS | FAIL from the post-fix re-test pass

Workflow phases (see docs/qa/README.md):
  1. Document  -> populate rows (status=Documented)
  2. Test      -> fill test_method/test_result/errors_found (status=Tested)
  3. Fix       -> fill fix_applied (status=Fixed)
  4. Re-test   -> fill retest_result (status=Verified)
"""

from __future__ import annotations

import csv
from pathlib import Path

FIELDS = [
    "id",
    "area",
    "feature",
    "user_story",
    "expected",
    "source_refs",
    "status",
    "test_method",
    "test_result",
    "errors_found",
    "fix_applied",
    "retest_result",
]

# Each entry: (id, area, feature, user_story, expected, source_refs,
#              status, test_method, test_result, errors_found,
#              fix_applied, retest_result)
ROWS: list[tuple[str, ...]] = [
    # ── App Shell ────────────────────────────────────────────────────────
    ("SHELL-01", "App Shell", "Global quit",
     "As a user on any screen, I want to press Q to quit so that I can exit quickly",
     "Pressing q triggers the quit action and closes the app",
     "app.py:38-39", "Documented", "", "", "", "", ""),
    ("SHELL-02", "App Shell", "Global help",
     "As a user, I want to open help from anywhere so that I can see keybindings",
     "Pressing ? pushes HelpScreen onto the stack",
     "app.py:40-47", "Documented", "", "", "", "", ""),
    ("SHELL-03", "App Shell", "Sidebar toggle",
     "As a user, I want to toggle the sidebar so that I gain horizontal space",
     "Ctrl+B calls toggle_collapsed() on every Sidebar widget",
     "app.py:41-53", "Documented", "", "", "", "", ""),
    ("SHELL-04", "App Shell", "Window title",
     "As a user, I want the header to show where I launched so that I know the working dir",
     "Title 'Dispatch'; subtitle 'Impala jobs - {cwd}' truncated to 40 chars with leading ellipsis",
     "app.py:64-76", "Documented", "", "", "", "", ""),
    ("SHELL-05", "App Shell", "Animation default off",
     "As an SSH user, I want minimal redraws so that the UI feels responsive",
     "Unless TEXTUAL_ANIMATIONS is set, animation_level is 'none' at startup",
     "app.py:58-62", "Documented", "", "", "", "", ""),
    ("SHELL-06", "App Shell", "Version mismatch warning",
     "As a user, I want to know when my install is stale so that I can re-run install",
     "If installed_version != running __version__, persistent warning 'Version mismatch...'",
     "app.py:79-81,170-177", "Documented", "", "", "", "", ""),
    ("SHELL-07", "App Shell", "Missing version file warning",
     "As a user with a broken install, I want a clear error so that I know to run install",
     "If version file unreadable, persistent warning 'Install incomplete: version file missing...'",
     "app.py:170-174", "Documented", "", "", "", "", ""),
    ("SHELL-08", "App Shell", "Dispatch home missing",
     "As a user without install, I want a startup error so that I know install is required",
     "If dispatch_home() missing, persistent error 'Dispatch is not installed for this user...'",
     "app.py:83-90", "Documented", "", "", "", "", ""),
    ("SHELL-09", "App Shell", "Startup route to Overview",
     "As a user launching Dispatch, I want to land on the jobs overview so that I supervise immediately",
     "On mount DashboardScreen is pushed as the initial screen",
     "app.py:93", "Documented", "", "", "", "", ""),
    ("SHELL-10", "App Shell", "Terminal too-small warning",
     "As a user on a tiny terminal, I want a warning so that I know layouts may break",
     "On mount/resize if width<80 or height<24 and not already warned, 10s warning shows size and minimum",
     "app.py:29-30,118-130", "Documented", "", "", "", "", ""),
    ("SHELL-11", "App Shell", "Kerberos TTL polling",
     "As a user, I want Kerberos expiry kept current so that launch guards stay accurate",
     "On mount refresh once then every 60s set app kerberos_ttl from kerberos.ticket_ttl_seconds()",
     "app.py:94-95,132-134", "Documented", "", "", "", "", ""),
    ("SHELL-12", "App Shell", "Test prefill seam",
     "As a test harness, I want to open New Job pre-filled so that I can script launches",
     "DISPATCH_TEST_PREFILL pointing to JSON dict opens NewJobScreen prefilled after first refresh",
     "app.py:96-116,212-214", "Documented", "", "", "", "", ""),
    ("SHELL-13", "App Shell", "Test prefill invalid file ignored",
     "As a test harness, I want bad prefill files ignored so that normal startup is not blocked",
     "Unreadable/invalid JSON path logs a warning and startup continues without New Job",
     "app.py:110-114", "Documented", "", "", "", "", ""),
    ("SHELL-14", "App Shell", "Command palette: Overview",
     "As a user, I want palette navigation to Overview so that I can return to the cockpit",
     "System command 'Overview' calls open_top_level('overview')",
     "app.py:136-143", "Documented", "", "", "", "", ""),
    ("SHELL-15", "App Shell", "Command palette: New Job",
     "As a user, I want palette navigation to New Job so that I can launch without keys",
     "System command 'New Job' calls open_top_level('new_job')",
     "app.py:144-147", "Documented", "", "", "", "", ""),
    ("SHELL-16", "App Shell", "Command palette: History",
     "As a user, I want palette navigation to History so that I find older jobs",
     "System command 'History' calls open_top_level('history')",
     "app.py:148-151", "Documented", "", "", "", "", ""),
    ("SHELL-17", "App Shell", "Command palette: Browse",
     "As a user, I want palette navigation to Browse so that I inspect Impala tables",
     "System command 'Browse metadata' calls open_top_level('browse')",
     "app.py:152-155", "Documented", "", "", "", "", ""),
    ("SHELL-18", "App Shell", "Command palette: kinit",
     "As a user, I want to refresh Kerberos from the palette so that I renew without leaving",
     "Suspends UI, runs interactive kinit, refreshes TTL; notifies refreshed Nm or 'still missing'",
     "app.py:156-168", "Documented", "", "", "", "", ""),
    ("SHELL-19", "App Shell", "Sidebar nav routing",
     "As a user, I want sidebar clicks to open destinations so that I can navigate",
     "NavItem.Selected overview/new_job/history/browse routes via open_top_level; active dest is no-op",
     "app.py:179-207", "Documented", "", "", "", "", ""),
    ("SHELL-20", "App Shell", "Sidebar View Logs routing",
     "As a user, I want sidebar View Logs to open the selected job so that I jump to logs",
     "view_logs uses selected job from Dashboard/History; warns to select a job first if none",
     "app.py:186-195,216-218,247-253", "Documented", "", "", "", "", ""),
    ("SHELL-21", "App Shell", "Navigation stack anchor",
     "As a user switching screens, I want Overview as base so that back nav is predictable",
     "open_top_level pops stack to <=2 before pushing; 'overview' only pops",
     "app.py:199-207,229-231", "Documented", "", "", "", "", ""),

    # ── Overview / Dashboard ─────────────────────────────────────────────
    ("OVW-01", "Overview", "Status strip counts",
     "As a supervisor, I want live job counts so that I see load at a glance",
     "Strip shows RUNNING n/2, FINISHED 7D (green or dim 0), FAILED 7D (red or dim 0)",
     "dashboard.py:254-270", "Documented", "", "", "", "", ""),
    ("OVW-02", "Overview", "Status strip Kerberos colors",
     "As a supervisor, I want Kerberos health in the strip so that I know if launches blocked",
     "Kerberos red MISSING when None, yellow when <3600s, green when >=3600s; mirrors app reactive",
     "dashboard.py:254-261,125-133", "Documented", "", "", "", "", ""),
    ("OVW-03", "Overview", "Jobs table layout",
     "As a supervisor, I want a dense jobs table so that I can scan active work",
     "Columns ID/Source/Destination/State/Elapsed; running first; running+finished-in-7d; cap 100 rows",
     "dashboard.py:114-116,238-244", "Documented", "", "", "", "", ""),
    ("OVW-04", "Overview", "Jobs empty state",
     "As a new user with no jobs, I want guidance so that I know how to start",
     "When 0 rows, table hides and empty shows 'No jobs in the last 7 days - press N to launch one'",
     "dashboard.py:101-102,340-342", "Documented", "", "", "", "", ""),
    ("OVW-05", "Overview", "Auto job refresh",
     "As a supervisor, I want the overview current so that states/elapsed update",
     "Refresh on mount and every 2s; failures notify 'Job refresh failed: {exc}'",
     "dashboard.py:127-128,155-189", "Documented", "", "", "", "", ""),
    ("OVW-06", "Overview", "Default detail selection",
     "As a supervisor, I want a log preview without clicking so that I watch active job",
     "First refresh with jobs auto-selects first Running else first job for the detail pane",
     "dashboard.py:169-174", "Documented", "", "", "", "", ""),
    ("OVW-07", "Overview", "Detail pane responsive hide",
     "As a user on a short terminal, I want the table prioritized so that nav stays usable",
     "When height<30 #detail-pane hidden; when >=30 shown",
     "dashboard.py:46-47,135-143", "Documented", "", "", "", "", ""),
    ("OVW-08", "Overview", "Detail pane placeholder",
     "As a user with no highlight, I want a clear prompt so that I know to select a row",
     "Detail title 'Select a job to preview its log' and blank log when no match",
     "dashboard.py:353-356", "Documented", "", "", "", "", ""),
    ("OVW-09", "Overview", "Detail pane log tail",
     "As a supervisor, I want a live log preview so that I spot failures fast",
     "Title shows id/state/elapsed + 'V for full logs'; up to 8 tail lines of last 4096 bytes",
     "dashboard.py:44-45,357-369,191-216", "Documented", "", "", "", "", ""),
    ("OVW-10", "Overview", "Row highlight updates detail",
     "As a supervisor, I want moving the cursor to update preview so that I scan quickly",
     "RowHighlighted caches key, sets detail job, async reads only the log tail (exclusive worker)",
     "dashboard.py:500-528", "Documented", "", "", "", "", ""),
    ("OVW-11", "Overview", "Filter open",
     "As a supervisor with many jobs, I want to filter so that I find a specific job",
     "Pressing / shows filter input with placeholder and focuses it",
     "dashboard.py:57-58,410-413", "Documented", "", "", "", "", ""),
    ("OVW-12", "Overview", "Filter matching",
     "As a supervisor, I want substring filtering so that partial matches work",
     "Each keystroke filters cached jobs case-insensitively on id/source/dest/state; running-first kept",
     "dashboard.py:272-288,425-430", "Documented", "", "", "", "", ""),
    ("OVW-13", "Overview", "Filter clear",
     "As a supervisor, I want to dismiss the filter so that I return to full list",
     "Esc when filter visible clears value, hides input, refocuses table, re-renders",
     "dashboard.py:58,415-423", "Documented", "", "", "", "", ""),
    ("OVW-14", "Overview", "Filter submit",
     "As a supervisor, I want Enter to leave the filter so that I use table keys again",
     "Submitting filter input moves focus to table without hiding the filter",
     "dashboard.py:432-434", "Documented", "", "", "", "", ""),
    ("OVW-15", "Overview", "Table movement j/k",
     "As a vim user, I want j/k to move selection so that I navigate without arrows",
     "j/k move cursor only when the table has focus; bindings hidden from footer",
     "dashboard.py:59-60,438-446", "Documented", "", "", "", "", ""),
    ("OVW-16", "Overview", "New Job shortcut",
     "As a user, I want a fast path to launch so that I avoid the mouse",
     "n or 'New Job [N]' button calls open_top_level('new_job')",
     "dashboard.py:52,108,467-468,486-488", "Documented", "", "", "", "", ""),
    ("OVW-17", "Overview", "View Logs shortcut",
     "As a supervisor, I want full logs for the selected job so that I diagnose issues",
     "v or 'View Logs [V]' opens JobDetailScreen for selected; no selection is a silent no-op",
     "dashboard.py:53,109,470-473,489-490", "Documented", "", "", "", "", ""),
    ("OVW-18", "Overview", "Cancel shortcut",
     "As a supervisor, I want to cancel the selected job so that I stop bad launches",
     "c or 'Cancel [C]' opens JobDetailScreen with cancel_on_mount=True; no selection is silent no-op",
     "dashboard.py:54,110,475-478,491-492", "Documented", "", "", "", "", ""),
    ("OVW-19", "Overview", "History shortcut",
     "As a user, I want finished-job history so that I review older work",
     "h opens History via open_top_level('history')",
     "dashboard.py:55,480-481", "Documented", "", "", "", "", ""),
    ("OVW-20", "Overview", "Browse shortcut",
     "As a user, I want metadata browse so that I inspect Impala without a job",
     "b opens Browser via open_top_level('browse')",
     "dashboard.py:56,483-484", "Documented", "", "", "", "", ""),
    ("OVW-21", "Overview", "Row activate opens detail",
     "As a supervisor, I want Enter on a row to open logs so that I drill in quickly",
     "RowSelected on non-empty row caches id and opens JobDetailScreen",
     "dashboard.py:494-498", "Documented", "", "", "", "", ""),
    ("OVW-22", "Overview", "State transition notifications",
     "As a supervisor, I want alerts when jobs finish so that I do not miss completions",
     "Running->terminal logs timestamped trail event and notifies 'Job {id} {state}'",
     "dashboard.py:371-382,145-151", "Documented", "", "", "", "", ""),
    ("OVW-23", "Overview", "Event trail startup",
     "As a supervisor, I want a recent activity hint so that I see the session started",
     "On mount trail shows '[HH:MM] dispatch started'; keeps <=3, displays latest",
     "dashboard.py:67,120,145-151", "Documented", "", "", "", "", ""),
    ("OVW-24", "Overview", "Initial focus",
     "As a user, I want keyboard control immediately so that I navigate without clicking",
     "On mount jobs table is focused; filter and empty state start hidden",
     "dashboard.py:118-119,129", "Documented", "", "", "", "", ""),

    # ── Sidebar ──────────────────────────────────────────────────────────
    ("SIDE-01", "Sidebar", "Navigation items",
     "As a user, I want labeled nav destinations so that I reach all major screens",
     "Items Overview/New Job/View Logs/History/Browse post NavItem.Selected with matching id",
     "sidebar.py:69-75,41-42", "Documented", "", "", "", "", ""),
    ("SIDE-02", "Sidebar", "Active item highlight",
     "As a user, I want to see where I am so that nav context is clear",
     "Item with item_id==active_screen gets nav-active (bold, primary bg, left border)",
     "sidebar.py:44-45,132-134", "Documented", "", "", "", "", ""),
    ("SIDE-03", "Sidebar", "Kerberos chip display",
     "As a user, I want Kerberos TTL in the sidebar so that I glance at health",
     "Chip mirrors app kerberos_ttl; 'KRB {ttl}' with krb-missing (None), krb-low (<3600s), else success",
     "sidebar.py:48-65,99-103", "Documented", "", "", "", "", ""),
    ("SIDE-04", "Sidebar", "Collapsed Kerberos icon",
     "As a user with collapsed sidebar, I want a compact indicator so that space is preserved",
     "Collapsed chip shows warn glyph if TTL None else check glyph",
     "sidebar.py:56-58", "Documented", "", "", "", "", ""),
    ("SIDE-05", "Sidebar", "Auto-collapse narrow",
     "As a user on a narrow terminal, I want auto-shrink so that content fits",
     "On resize, width<100 sets collapsed True; width>=100 sets collapsed False",
     "sidebar.py:105-116", "Documented", "", "", "", "", ""),
    ("SIDE-06", "Sidebar", "Collapsed presentation",
     "As a user, I want icon-only sidebar so that labels do not wrap",
     "Collapsed: width 5, brand 'D', version hidden, help '?', nav icon-only, footer centered",
     "sidebar.py:121-130", "Documented", "", "", "", "", ""),
    ("SIDE-07", "Sidebar", "Footer version and help",
     "As a user, I want version/help hints so that I know the build and how to get help",
     "Expanded footer shows 'v{version}' and '? help'; collapses help hint to '?'",
     "sidebar.py:90-93,126-127", "Documented", "", "", "", "", ""),
    ("SIDE-08", "Sidebar", "Manual collapse toggle",
     "As a user, I want to force collapse/expand so that I control layout",
     "Ctrl+B flips collapsed; watch_collapsed updates brand/version/help/chip/nav labels",
     "app.py:49-53,sidebar.py:118-130", "Documented", "", "", "", "", ""),

    # ── New Job ──────────────────────────────────────────────────────────
    ("NJ-01", "New Job", "Legal cells matrix",
     "As a user, I want to see allowed Source x Destination so that I choose valid config",
     "Collapsible legal-cells table: SqlFile->all; SqlTemplate->Table only; ExistingTable->Csv only",
     "new_job.py:142-144,manifest.py:56-62", "Documented", "", "", "", "", ""),
    ("NJ-02", "New Job", "Matrix toggle",
     "As a user, I want to show/hide the matrix so that I save screen space",
     "M toggles #matrix-collapsible collapsed state",
     "new_job.py:37,276-278", "Documented", "", "", "", "", ""),
    ("NJ-03", "New Job", "Source selection",
     "As a user, I want to pick the source so that the form matches my data",
     "Source radio SqlFile(default)/SqlTemplate/ExistingTable; change updates visibility+validation",
     "new_job.py:78-81,265-268,341-383", "Documented", "", "", "", "", ""),
    ("NJ-04", "New Job", "Destination selection",
     "As a user, I want to pick the destination so that results land where I need",
     "Destination radio Table/Csv(default)/Table+Csv; illegal destinations disabled for source",
     "new_job.py:84-87,345-349", "Documented", "", "", "", "", ""),
    ("NJ-05", "New Job", "Illegal SqlTemplate->Csv disabled",
     "As a user, I must not launch SqlTemplate to Csv so that monthly jobs only make tables",
     "SqlTemplate disables Csv and Table+Csv radios; hint 'SqlTemplate supports Table only'",
     "new_job.py:376-377,348", "Documented", "", "", "", "", ""),
    ("NJ-06", "New Job", "Illegal ExistingTable->Table disabled",
     "As a user, I must not create a table from ExistingTable so that only CSV export is offered",
     "ExistingTable disables Table and Table+Csv radios; hint 'ExistingTable supports Csv only'",
     "new_job.py:379-381,348", "Documented", "", "", "", "", ""),
    ("NJ-07", "New Job", "Auto-correct illegal destination",
     "As a user switching source, I want illegal dest auto-corrected so that I am never stuck",
     "If current dest illegal for new source, first legal destination is auto-selected (deferred timer)",
     "new_job.py:385-397", "Documented", "", "", "", "", ""),
    ("NJ-08", "New Job", "SQL file picker",
     "As a user, I want to pick a .sql file from CWD without typing so that launch is faster",
     "SqlFile/SqlTemplate + cwd has *.sql + not prefilled: table lists File/Detected/Modified; select fills path",
     "new_job.py:166-225,361-363", "Documented", "", "", "", "", ""),
    ("NJ-09", "New Job", "SQL file default path",
     "As a user opening New Job, I want a sensible default path so that I launch quickly",
     "Default #sql-file is first sorted *.sql in launch_cwd else launch_cwd/query.sql",
     "new_job.py:246-248", "Documented", "", "", "", "", ""),
    ("NJ-10", "New Job", "SQL file path hint",
     "As a user editing the path, I want existence feedback so that I catch typos",
     "#path-hint shows check/cross plus dim filename; updates on sql-file change",
     "new_job.py:399-409,273-274", "Documented", "", "", "", "", ""),
    ("NJ-11", "New Job", "SQL file inline validation",
     "As a user, I want live SQL file status so that I know the path resolves",
     "Existing path 'check SQL file found'; missing nonempty path 'cross SQL file not found'",
     "new_job.py:294-298", "Documented", "", "", "", "", ""),
    ("NJ-12", "New Job", "SQL content auto-detect",
     "As a user, I want SqlTemplate auto-detected so that source is set correctly",
     "Both placeholders -> detected SqlTemplate and src radio set; otherwise SqlFile",
     "new_job.py:435-447,sql.py:9-12", "Documented", "", "", "", "", ""),
    ("NJ-13", "New Job", "Existing table field",
     "As a user exporting an existing table, I want to name it so that export targets right data",
     "ExistingTable shows #row-existing-table; launch needs nonempty name or schema.table fallback",
     "new_job.py:364,460-462,478-482", "Documented", "", "", "", "", ""),
    ("NJ-14", "New Job", "Schema and table fields",
     "As a user creating a table, I want schema/table inputs so that target is explicit",
     "Schema(default aa_enc)/Table(default dispatch_result) shown for Table/Table+Csv or SqlTemplate",
     "new_job.py:103-109,354-366", "Documented", "", "", "", "", ""),
    ("NJ-15", "New Job", "Template date range",
     "As a user running a monthly template, I want start/end dates so that partitions are right",
     "SqlTemplate shows Start/End date defaults (month bounds); passed to orchestrator as MM/DD/YYYY",
     "new_job.py:111-117,236-244,496-498", "Documented", "", "", "", "", ""),
    ("NJ-16", "New Job", "Email and subject",
     "As a user, I want notification email/subject so that completion is reported",
     "Email defaults DISPATCH_EMAIL; Subject default 'Dispatch Job'; both always visible",
     "new_job.py:119-129", "Documented", "", "", "", "", ""),
    ("NJ-17", "New Job", "Email inline validation",
     "As a user, I want invalid emails flagged so that notifications are addressed",
     "Nonempty email must contain @ and . in domain; valid 'check Email' else 'cross Invalid email format'",
     "new_job.py:299-304,322-324", "Documented", "", "", "", "", ""),
    ("NJ-18", "New Job", "Kerberos inline status",
     "As a user, I want Kerberos health visible so that I renew before launch",
     "Missing -> 'cross Kerberos missing'; TTL<300 -> 'warn Kerberos TTL low'; else 'check Kerberos'",
     "new_job.py:155-156,305-310", "Documented", "", "", "", "", ""),
    ("NJ-19", "New Job", "Kerberos launch gate",
     "As a user without valid Kerberos, I must not launch so that jobs do not fail auth",
     "Launch disabled when ttl None or <300; validate returns missing/under-5-minutes message",
     "new_job.py:411-414,456-459", "Documented", "", "", "", "", ""),
    ("NJ-20", "New Job", "Kerberos renewal (kinit)",
     "As a user, I want kinit from the form so that I renew tickets",
     "K suspends TUI, runs kinit, refreshes TTL+sidebar; notify refreshed Nm or still missing",
     "new_job.py:619-628", "Documented", "", "", "", "", ""),
    ("NJ-21", "New Job", "Validation summary",
     "As a user, I want a launch-readiness summary so that I see blockers at a glance",
     "#validation-summary 'Ready to launch' or 'N issue(s): {first}(+M more)'",
     "new_job.py:331-339,313-329", "Documented", "", "", "", "", ""),
    ("NJ-22", "New Job", "Illegal combination launch block",
     "As a user, I must not launch illegal Source/Destination so that orchestrators get valid cells",
     "validate returns 'Illegal Source/Destination cell: {S}/{D}'",
     "new_job.py:317-318,452-453,manifest.py:56-62", "Documented", "", "", "", "", ""),
    ("NJ-23", "New Job", "Running job cap",
     "As a user, I must not exceed concurrency so that cluster load is bounded",
     ">=2 Running -> 'Already at the 2-Job concurrency cap; wait for one to finish' (RUNNING_CAP=2)",
     "new_job.py:454-455,jobs.py:14,63-64", "Documented", "", "", "", "", ""),
    ("NJ-24", "New Job", "Malformed template SQL",
     "As a user, I must fix half-filled placeholders so that monthly jobs do not mis-run",
     "Launch blocks 'SQL contains only one of {date_inicio}/{date_fim}...' when exactly one present",
     "new_job.py:467-468,sql.py:19-24", "Documented", "", "", "", "", ""),
    ("NJ-25", "New Job", "Incomplete SqlTemplate",
     "As a user selecting SqlTemplate, I must include both placeholders so that substitution works",
     "Launch blocks 'SqlTemplate requires both {date_inicio} and {date_fim}' when either missing",
     "new_job.py:469-470,sql.py:15-16", "Documented", "", "", "", "", ""),
    ("NJ-26", "New Job", "Unreadable SQL file",
     "As a user, I must provide a readable SQL file so that the job can start",
     "Launch blocks 'SQL file is unreadable'; preview shows 'Cannot read SQL file: {path}'",
     "new_job.py:416-422,464-466,549-550", "Documented", "", "", "", "", ""),
    ("NJ-27", "New Job", "Existing table required",
     "As a user with ExistingTable, I must name the table so that export has a source",
     "Launch blocks 'Existing table name is required' when existing-table blank (schema.table fallback otherwise)",
     "new_job.py:460-462", "Documented", "", "", "", "", ""),
    ("NJ-28", "New Job", "Preview action",
     "As a user, I want to preview SQL before launch so that I verify the query",
     "P or 'Preview SQL [P]' opens PreviewScreen without full validate",
     "new_job.py:36,507-535", "Documented", "", "", "", "", ""),
    ("NJ-29", "New Job", "Preview blocked for ExistingTable",
     "As a user with ExistingTable, I understand preview does not apply so that I am not shown empty SQL",
     "Preview shows 'Preview is not available for ExistingTable source.' and does not push screen",
     "new_job.py:511-513", "Documented", "", "", "", "", ""),
    ("NJ-30", "New Job", "Preview SqlTemplate per-month",
     "As a user, I want monthly template preview so that I see resolved SQL",
     "SqlTemplate preview: comment headers per month, placeholders replaced, schema.table_temp_YYYYMM",
     "new_job.py:517-522,sql.py:77-95", "Documented", "", "", "", "", ""),
    ("NJ-31", "New Job", "Preview SqlFile table wrap",
     "As a user, I want to see DROP/CREATE wrapper so that table jobs match DDL",
     "Non-DDL SqlFile preview wraps DROP/CREATE PARQUET LOCATION ... AS; self-contained DDL verbatim",
     "new_job.py:523-528,sql.py:29-63", "Documented", "", "", "", "", ""),
    ("NJ-32", "New Job", "Edit SQL in $EDITOR",
     "As a user, I want to edit the SQL in $EDITOR so that I fix queries in place",
     "E suspends TUI, runs $EDITOR (default vi) on path, clears cache, re-detects source",
     "new_job.py:33,612-617", "Documented", "", "", "", "", ""),
    ("NJ-33", "New Job", "Launch confirmation",
     "As a user, I want to confirm before launch so that accidental launches are prevented",
     "L/Launch validates then pushes danger ConfirmScreen with summary; Y/Enter launches, N/Esc aborts",
     "new_job.py:35,546-610,confirm.py:14-19", "Documented", "", "", "", "", ""),
    ("NJ-34", "New Job", "Successful launch feedback",
     "As a user, I want feedback when a job starts so that I know it was queued",
     "After confirm: manifest created, runner launched, notify+warning 'Launched Job {id}'; defaults saved",
     "new_job.py:563-574,727-735", "Documented", "", "", "", "", ""),
    ("NJ-35", "New Job", "Saved form defaults",
     "As a returning user, I want prior schema/email/subject restored so that repeats are faster",
     "On mount read_form_defaults fills schema/email/subject if present",
     "new_job.py:711-725", "Documented", "", "", "", "", ""),
    ("NJ-36", "New Job", "Prefill mode",
     "As a user re-running a job, I want the form prefilled so that I tweak and relaunch",
     "prefill dict sets inputs/radios after refresh; matrix collapsed; file picker hidden",
     "new_job.py:630-678,361", "Documented", "", "", "", "", ""),
    ("NJ-37", "New Job", "Navigation back",
     "As a user, I want to leave New Job without launching so that I return to prior screen",
     "Escape or B pops the screen",
     "new_job.py:31-32", "Documented", "", "", "", "", ""),

    # ── SQL Preview ──────────────────────────────────────────────────────
    ("PREV-01", "SQL Preview", "Syntax display",
     "As a user, I want highlighted SQL so that I read the query easily",
     "PreviewScreen writes sql to #preview-body RichLog with SQL lexer, line numbers, wrap, ansi_dark",
     "preview.py:14-24,82-84", "Documented", "", "", "", "", ""),
    ("PREV-02", "SQL Preview", "Metadata header",
     "As a user, I want preview context so that I know source/destination/target",
     "Header breadcrumb 'New Job / SQL Preview', Target schema.table, and 'source -> dest'",
     "preview.py:60-71", "Documented", "", "", "", "", ""),
    ("PREV-03", "SQL Preview", "Line count status",
     "As a user, I want preview size context so that I know how much to review",
     "#preview-status shows '{N} lines - review before launching'",
     "preview.py:85-88", "Documented", "", "", "", "", ""),
    ("PREV-04", "SQL Preview", "Copy SQL",
     "As a user, I want to copy the preview so that I paste elsewhere",
     "Y or 'Copy SQL [Y]' copies body; notify 'SQL copied to clipboard' or 'Copy unavailable...'",
     "preview.py:32,93-98", "Documented", "", "", "", "", ""),
    ("PREV-05", "SQL Preview", "Back navigation",
     "As a user, I want to return to New Job so that I launch or edit",
     "Esc, B, Enter, or Back pops the screen",
     "preview.py:29-31,90-91,100-102", "Documented", "", "", "", "", ""),

    # ── Confirm Dialog ───────────────────────────────────────────────────
    ("CONF-01", "Confirm Dialog", "Basic confirm",
     "As a user, I want a simple yes/no modal so that I approve actions",
     "Y/Enter confirms (True), N/Esc cancels (False); initial focus on confirm button",
     "confirm.py:14-19,67-71,83-94", "Documented", "", "", "", "", ""),
    ("CONF-02", "Confirm Dialog", "Danger styling",
     "As a user, I want dangerous confirms distinct so that I pause",
     "danger=True: bold red title, error confirm button (used for Launch Job)",
     "confirm.py:40-47,63-64", "Documented", "", "", "", "", ""),
    ("CONF-03", "Confirm Dialog", "Custom labels",
     "As a user, I want action-specific buttons so that intent is clear",
     "Launch confirm uses confirm 'Launch' and cancel 'Review'",
     "confirm.py:27-28,new_job.py:605-606", "Documented", "", "", "", "", ""),
    ("CONF-04", "Confirm Dialog", "Typed confirmation",
     "As a user, I want to type a resource name for high-risk actions so that mis-clicks cannot confirm",
     "required_confirmation_text shows Input; confirm only on exact match; mismatch updates red help",
     "confirm.py:49-53,67-69,84-90", "Documented", "", "", "", "", ""),
    ("CONF-05", "Confirm Dialog", "Input submit confirm",
     "As a user confirming via keyboard, I want Enter in the field to submit so that I avoid clicking",
     "Input.Submitted on #confirm-input triggers action_confirm",
     "confirm.py:79-81", "Documented", "", "", "", "", ""),

    # ── SQL Parsing ──────────────────────────────────────────────────────
    ("SQL-01", "SQL Parsing", "detect_source",
     "As a user, I want consistent source detection so that UI matches file content",
     "Both placeholders -> SqlTemplate else SqlFile",
     "sql.py:9-12", "Documented", "", "", "", "", ""),
    ("SQL-02", "SQL Parsing", "malformed template detection",
     "As a user, I want single-placeholder files flagged so that typos are caught",
     "is_malformed_template True when exactly one placeholder present",
     "sql.py:19-24", "Documented", "", "", "", "", ""),
    ("SQL-03", "SQL Parsing", "self-contained DDL",
     "As a user with CREATE/INSERT SQL, I want no double-wrapping so that DDL runs as written",
     "is_self_contained_ddl True when first keyword is create/drop/insert/alter/truncate/merge; WITH=SELECT",
     "sql.py:26-50", "Documented", "", "", "", "", ""),
    ("SQL-04", "SQL Parsing", "month_range",
     "As a user previewing templates, I want one block per month so that monthly jobs are clear",
     "month_range iterates first-of-month from start through end inclusive",
     "sql.py:66-74", "Documented", "", "", "", "", ""),

    # ── Job Detail ───────────────────────────────────────────────────────
    ("JD-01", "Job Detail", "Screen title",
     "As a user, I want to see which job I view so that I orient myself",
     "Title breadcrumb 'Overview /' plus bold 'Job {full id}'",
     "job_detail.py:84-86", "Documented", "", "", "", "", ""),
    ("JD-02", "Job Detail", "Summary placeholders",
     "As a user opening before data loads, I want safe defaults so that no garbage shows",
     "State/Source/Destination/Started/Elapsed/CSV initially show '--'",
     "job_detail.py:91-98", "Documented", "", "", "", "", ""),
    ("JD-03", "Job Detail", "Manifest refresh",
     "As a user, I want metadata current so that I see live status",
     "Polls manifest and log every 1.0s via set_interval",
     "job_detail.py:127", "Documented", "", "", "", "", ""),
    ("JD-04", "Job Detail", "Manifest mtime cache",
     "As a user on slow SSH, I want efficient updates so that unchanged manifests are not reparsed",
     "Unchanged mtime reuses cached manifest instead of reloading JSON",
     "job_detail.py:138-146", "Documented", "", "", "", "", ""),
    ("JD-05", "Job Detail", "Unreadable manifest",
     "As a user viewing a corrupt job, I want graceful failure so that I am not crashed",
     "If manifest stat/load fails, snapshot None and UI not updated that tick",
     "job_detail.py:134-144,185-187", "Documented", "", "", "", "", ""),
    ("JD-06", "Job Detail", "Source display",
     "As a user, I want to see job origin so that I verify inputs",
     "Source shows truncated table_name, else sql path, else type, else '--'",
     "job_detail.py:201-204", "Documented", "", "", "", "", ""),
    ("JD-07", "Job Detail", "Destination display",
     "As a user, I want to see the target so that I know where output goes",
     "Destination '{type} -> {schema.table}' when both exist else type or '--'",
     "job_detail.py:205-211", "Documented", "", "", "", "", ""),
    ("JD-08", "Job Detail", "Path truncation",
     "As a user with long paths, I want readable summary so that layout holds",
     "Paths >40 chars render as ellipsis + last 40 chars",
     "job_detail.py:372-376", "Documented", "", "", "", "", ""),
    ("JD-09", "Job Detail", "State formatting",
     "As a user, I want scannable state so that status is obvious",
     "format_state symbol+color; Failed appends ' - {error_code}' when classified",
     "formatting.py:67-73,job_detail.py:213-215", "Documented", "", "", "", "", ""),
    ("JD-10", "Job Detail", "Started timestamp",
     "As a user, I want a readable start time so that I know when it began",
     "Started shows local 'YYYY-MM-DD HH:MM' or '--'",
     "formatting.py:48-54,job_detail.py:226-228", "Documented", "", "", "", "", ""),
    ("JD-11", "Job Detail", "Elapsed time",
     "As a user, I want elapsed duration so that I judge runtime",
     "Running live elapsed; finished uses finished-started; invalid '--'; formats Ns/Nm Ns/Nh Nm",
     "formatting.py:17-36,job_detail.py:229", "Documented", "", "", "", "", ""),
    ("JD-12", "Job Detail", "CSV path",
     "As a user, I want CSV location when relevant so that I find exports",
     "Csv/Table+Csv with csv_path shows truncated path; else dim 'n/a (table-only)'",
     "job_detail.py:230-235", "Documented", "", "", "", "", ""),
    ("JD-13", "Job Detail", "Running stream indicator",
     "As a user watching running job, I want to know logs are live so that I trust the tail",
     "Running shows green 'Streaming logs... (auto-scroll)' when follow on, yellow '[PAUSED]' when off",
     "job_detail.py:252-258", "Documented", "", "", "", "", ""),
    ("JD-14", "Job Detail", "Finished stream indicator",
     "As a user viewing finished job, I want terminal status so that complete vs streaming is clear",
     "Non-running shows Complete/Failed(red)/Cancelled(dim) in log header",
     "job_detail.py:218-224", "Documented", "", "", "", "", ""),
    ("JD-15", "Job Detail", "Log tail incremental read",
     "As a user, I want new lines appended so that large logs stay responsive",
     "Each refresh reads run.log from _tail_offset; only new bytes appended",
     "job_detail.py:148-161,279-292", "Documented", "", "", "", "", ""),
    ("JD-16", "Job Detail", "No log yet",
     "As a user on fresh job, I want empty panel without errors so that I wait for output",
     "Missing/empty log writes nothing; offset unchanged",
     "job_detail.py:148-161,279-281", "Documented", "", "", "", "", ""),
    ("JD-17", "Job Detail", "Log rotation reset",
     "As a user when log shrinks, I want tailing to recover so that I keep seeing output",
     "If size < stored offset, offset resets to 0 before read",
     "job_detail.py:152-154", "Documented", "", "", "", "", ""),
    ("JD-18", "Job Detail", "Log line styling",
     "As a user, I want readable log format so that comments/timestamps are distinct",
     "Lines starting -- dimmed; bracketed timestamp prefixes dimmed",
     "formatting.py:76-83,job_detail.py:378-380", "Documented", "", "", "", "", ""),
    ("JD-19", "Job Detail", "UTF-8 log decoding",
     "As a user with imperfect bytes, I want tail to keep working so that one bad char does not break view",
     "Log opened with encoding utf-8, errors=replace",
     "job_detail.py:156", "Documented", "", "", "", "", ""),
    ("JD-20", "Job Detail", "Follow mode default",
     "As a user, I want auto-scroll by default so that I see latest output",
     "follow_mode starts True; new lines trigger scroll_end when on",
     "job_detail.py:43,299-300", "Documented", "", "", "", "", ""),
    ("JD-21", "Job Detail", "Toggle follow",
     "As a user, I want to pause/resume auto-scroll so that I read earlier lines",
     "Space or hidden f toggles follow; re-enabling scrolls to bottom; indicator updates",
     "job_detail.py:305-308,302-303", "Documented", "", "", "", "", ""),
    ("JD-22", "Job Detail", "Jump log top",
     "As a user, I want to jump to oldest lines so that I review from start",
     "g sets follow off and scrolls log to top",
     "job_detail.py:310-312", "Documented", "", "", "", "", ""),
    ("JD-23", "Job Detail", "Jump log bottom",
     "As a user, I want to jump to latest lines so that I resume tailing",
     "G sets follow on and scrolls log to bottom",
     "job_detail.py:314-316", "Documented", "", "", "", "", ""),
    ("JD-24", "Job Detail", "In-memory log cap",
     "As a user on chatty jobs, I want bounded UI so that memory does not grow",
     "Tail deque keeps at most 200 lines; older evicted",
     "job_detail.py:50,283-287", "Documented", "", "", "", "", ""),
    ("JD-25", "Job Detail", "Truncation hint",
     "As a user when early lines drop, I want to know how much is hidden so that I am not misled",
     "When evicted, dim hint '[... N earlier lines not shown]'; hidden when none",
     "job_detail.py:293-298", "Documented", "", "", "", "", ""),
    ("JD-26", "Job Detail", "Log search toggle",
     "As a user, I want to search the log so that I find errors quickly",
     "/ toggles hidden search input; open focuses; close clears query and refocuses log",
     "job_detail.py:318-326,120", "Documented", "", "", "", "", ""),
    ("JD-27", "Job Detail", "Log search highlight",
     "As a user typing search, I want matches emphasized so that they stand out",
     "Active search wraps newly appended matching lines in reverse markup (case-insensitive)",
     "job_detail.py:288-291,328-330", "Documented", "", "", "", "", ""),
    ("JD-28", "Job Detail", "Log search submit",
     "As a user, I want Enter to close search so that I return to scrolling",
     "Submitting search input toggles search off",
     "job_detail.py:332-334", "Documented", "", "", "", "", ""),
    ("JD-29", "Job Detail", "Failed error classification",
     "As a user of failed job, I want the failure categorized so that I know what went wrong",
     "First Failed snapshot scans last ~64KB/50 lines for SYNTAX/TABLE_NOT_FOUND/MEMORY/AUTH/QUEUE",
     "errors.py:43-54,job_detail.py:164-166", "Documented", "", "", "", "", ""),
    ("JD-30", "Job Detail", "Error banner classified",
     "As a user, I want actionable failure context so that I fix and retry",
     "Failed with code: bold red '{code}: {first matching line<=120}' + dim suggestion",
     "errors.py:63-76,57-60,job_detail.py:266-271", "Documented", "", "", "", "", ""),
    ("JD-31", "Job Detail", "Error banner unclassified",
     "As a user when failure unknown, I want a generic prompt so that I still read logs",
     "Failed without code: 'Job failed. Check log for details.'",
     "job_detail.py:272-275", "Documented", "", "", "", "", ""),
    ("JD-32", "Job Detail", "Error banner hidden",
     "As a user on non-failed job, I want no false alarm so that banner does not distract",
     "Banner hidden unless state Failed",
     "job_detail.py:260-265,122", "Documented", "", "", "", "", ""),
    ("JD-33", "Job Detail", "Status line",
     "As a user, I want a concise footer status so that I see outcome at a glance",
     "Status shows state; Failed adds 'exit {code or ?}'; adds 'finished {ts}' when finished_at set",
     "job_detail.py:245-250", "Documented", "", "", "", "", ""),
    ("JD-34", "Job Detail", "Cancel button visibility",
     "As a user, I want cancel only when applicable so that I am not offered impossible actions",
     "Cancel button and C shown/enabled only for Running or Pending",
     "job_detail.py:67-68,237-238", "Documented", "", "", "", "", ""),
    ("JD-35", "Job Detail", "Clone button visibility",
     "As a user, I want to reuse finished settings so that relaunch is faster",
     "Clone button and R appear only for Succeeded/Failed/Cancelled",
     "job_detail.py:69-70,239-240", "Documented", "", "", "", "", ""),
    ("JD-36", "Job Detail", "Cancel confirmation",
     "As a user cancelling running job, I want a safety prompt so that I do not kill accidentally",
     "Running with pid: confirm to cancel id and SIGTERM pgid; labels 'Cancel Job'/'Keep Running'",
     "job_detail.py:386-420", "Documented", "", "", "", "", ""),
    ("JD-37", "Job Detail", "Cancel success feedback",
     "As a user who confirmed cancel, I want acknowledgement so that I know request sent",
     "SIGTERM to pgid, warning notify 'Cancellation requested for Job {id}', status updates",
     "job_detail.py:396-398", "Documented", "", "", "", "", ""),
    ("JD-38", "Job Detail", "Cancel declined",
     "As a user who backs out, I want no side effects so that the job keeps running",
     "Confirmation False -> no signal sent and status unchanged",
     "job_detail.py:393-395", "Documented", "", "", "", "", ""),
    ("JD-39", "Job Detail", "Cancel pending no-op",
     "As a user on Pending job, I want predictable behavior so that cancel is not broken",
     "Cancel UI available for Pending but flow acts only when Running with pid; else returns",
     "job_detail.py:391-392", "Documented", "", "", "", "", ""),
    ("JD-40", "Job Detail", "Cancel manifest missing",
     "As a user if manifest disappears, I want a safe no-op so that app does not crash",
     "Manifest load failure in cancel flow returns without UI changes",
     "job_detail.py:387-390", "Documented", "", "", "", "", ""),
    ("JD-41", "Job Detail", "Cancel on mount",
     "As a user routed from Overview cancel, I want the confirm immediately so that I cancel in one step",
     "cancel_on_mount=True runs action_cancel on mount",
     "job_detail.py:124-125", "Documented", "", "", "", "", ""),
    ("JD-42", "Job Detail", "Cancel worker exclusivity",
     "As a user, I want one cancel flow so that duplicate modals do not stack",
     "action_cancel runs _cancel_flow in exclusive worker 'cancel-flow'",
     "job_detail.py:382-384", "Documented", "", "", "", "", ""),
    ("JD-43", "Job Detail", "Copy job ID",
     "As a user, I want to copy the job ID so that I share/reference it",
     "Y copies full job_id and notifies 'Job ID copied to clipboard'",
     "job_detail.py:336-339", "Documented", "", "", "", "", ""),
    ("JD-44", "Job Detail", "Copy ID fallback",
     "As a user without clipboard, I want the ID shown so that I copy manually",
     "Clipboard failure shows info notify with job ID body, title 'Job ID'",
     "job_detail.py:340-341", "Documented", "", "", "", "", ""),
    ("JD-45", "Job Detail", "Clone job",
     "As a user, I want to clone a finished job so that I rerun same params",
     "R/Clone loads manifest and opens New Job prefill with source/dest/email/subject/dates",
     "job_detail.py:343-353,356-370", "Documented", "", "", "", "", ""),
    ("JD-46", "Job Detail", "Clone failure",
     "As a user when clone cannot load, I want a clear error so that I know why",
     "Manifest load exception shows error notify 'Cannot clone: {exc}' and does not open New Job",
     "job_detail.py:346-350", "Documented", "", "", "", "", ""),
    ("JD-47", "Job Detail", "Navigate back",
     "As a user, I want to return to previous screen so that I keep supervising",
     "B, Esc, or Back calls app.pop_screen()",
     "job_detail.py:31-33,425-426", "Documented", "", "", "", "", ""),

    # ── History ──────────────────────────────────────────────────────────
    ("HIST-01", "History", "Scope label",
     "As a user, I want to know what History contains so that I do not confuse it with recent jobs",
     "Section title 'Job History - finished more than 7 days ago'",
     "history.py:49-51,jobs.py:13,77-84", "Documented", "", "", "", "", ""),
    ("HIST-02", "History", "Initial load",
     "As a user opening History, I want older finished jobs listed so that I audit past work",
     "On mount loads history_jobs() async, populates filter cache, renders table",
     "history.py:76-83", "Documented", "", "", "", "", ""),
    ("HIST-03", "History", "Table columns",
     "As a user, I want key fields so that I scan many jobs",
     "Columns ID/Table-Target/State/Finished At; row cursor enabled",
     "history.py:77-79", "Documented", "", "", "", "", ""),
    ("HIST-04", "History", "Search filter",
     "As a user, I want to filter history so that I find a specific job",
     "Search filters case-insensitively on id/schema.table/finished_at; resets to page 0",
     "history.py:89-94,101-110", "Documented", "", "", "", "", ""),
    ("HIST-05", "History", "Sort cycle",
     "As a user, I want to reorder history so that I browse by different keys",
     "S cycles date->state->table; wrapping to date toggles asc/desc; indicator shows mode+arrow",
     "history.py:173-180,161-163", "Documented", "", "", "", "", ""),
    ("HIST-06", "History", "Default sort",
     "As a user, I want recent history first so that newest archived appears first",
     "Initial sort date descending",
     "history.py:39-40,53", "Documented", "", "", "", "", ""),
    ("HIST-07", "History", "Pagination",
     "As a user with many jobs, I want paging so that the table stays readable",
     "Page size 17; ] next, [ prev; footer 'Showing s-e of total' and 'Page N of M'",
     "history.py:18,192-201,148-159", "Documented", "", "", "", "", ""),
    ("HIST-08", "History", "Row display ID",
     "As a user, I want compact IDs so that columns fit",
     "ID uses short format_job_id (drops first 9 chars when len>20)",
     "formatting.py:39-45,history.py:203-205", "Documented", "", "", "", "", ""),
    ("HIST-09", "History", "Row display target",
     "As a user, I want a recognizable target so that I know which table/file",
     "Target shows table_name else csv_path basename, truncated to 25 chars",
     "history.py:124-131", "Documented", "", "", "", "", ""),
    ("HIST-10", "History", "Row display state",
     "As a user, I want consistent state styling so that outcomes match other screens",
     "State uses format_state without error-code suffix",
     "formatting.py:67-73,history.py:132", "Documented", "", "", "", "", ""),
    ("HIST-11", "History", "Row display finished",
     "As a user, I want when the job ended so that I correlate incidents",
     "Finished uses local format_timestamp or '--'",
     "formatting.py:48-54,history.py:133", "Documented", "", "", "", "", ""),
    ("HIST-12", "History", "Status summary",
     "As a user, I want a count of visible jobs so that I know filter impact",
     "Status shows '{total} finished job(s)' plus 'matching \"{needle}\"' when searching",
     "history.py:153-156", "Documented", "", "", "", "", ""),
    ("HIST-13", "History", "Empty state",
     "As a user with no matches, I want guidance so that I know where else to look",
     "0 rows hides table+pagination; message 'No history found - adjust your search...'; focus to search",
     "history.py:137-142,63-64", "Documented", "", "", "", "", ""),
    ("HIST-14", "History", "Initial empty focus",
     "As a user with no history, I want to filter immediately so that I search without extra clicks",
     "No jobs on mount focuses search input instead of table",
     "history.py:84-87", "Documented", "", "", "", "", ""),
    ("HIST-15", "History", "View logs selection",
     "As a user, I want to open logs for a row so that I inspect an old job",
     "Enter/View Logs/row select pushes JobDetailScreen(job_id) without cancel_on_mount",
     "history.py:223-226,207-210", "Documented", "", "", "", "", ""),
    ("HIST-16", "History", "View logs no selection",
     "As a user with no valid row, I want a no-op so that I am not sent to a blank detail",
     "view_logs does nothing when no row key resolved",
     "history.py:224-226,212-221", "Documented", "", "", "", "", ""),
    ("HIST-17", "History", "Keyboard navigation",
     "As a user, I want vim-style movement so that I select jobs quickly",
     "Hidden j/k move cursor only when table has focus",
     "history.py:182-185,187-190", "Documented", "", "", "", "", ""),
    ("HIST-18", "History", "Navigate back",
     "As a user, I want to leave History so that I return to the cockpit",
     "B, Esc, or Back pops the screen",
     "history.py:23-24,231-232", "Documented", "", "", "", "", ""),

    # ── Help ─────────────────────────────────────────────────────────────
    ("HELP-01", "Help", "Open help",
     "As a user, I want a shortcut reference so that I learn keys without leaving",
     "Global ? pushes modal HelpScreen",
     "help.py,app.py:46-47", "Documented", "", "", "", "", ""),
    ("HELP-02", "Help", "Quick reference header",
     "As a user, I want top-level shortcuts so that common nav is fast",
     "Top static 'Quick Reference' with N/V/H/B/Q",
     "help.py:10-12", "Documented", "", "", "", "", ""),
    ("HELP-03", "Help", "Full shortcut list",
     "As a user, I want per-screen bindings so that I use advanced features",
     "Body lists Global/Overview/New Job/Preview/Job Detail/History/Browser shortcuts",
     "help.py:14-66", "Documented", "", "", "", "", ""),
    ("HELP-04", "Help", "Close help",
     "As a user, I want to dismiss help quickly so that I return to work",
     "Esc or ? dismisses; footer 'Press Esc or ? to close.'",
     "help.py:71-74,66", "Documented", "", "", "", "", ""),
    ("HELP-05", "Help", "Job Detail documented keys match",
     "As a user on Job Detail, I want help to match behavior so that help is trustworthy",
     "Help lists Space/F follow, g/G, / search, Y copy, R clone, C cancel, B/Esc back",
     "help.py:45-52", "Documented", "", "", "", "", ""),
    ("HELP-06", "Help", "History documented keys match",
     "As a user on History, I want help to match behavior so that help is trustworthy",
     "Help lists S sort, [ ] paging, Enter view logs, B/Esc back",
     "help.py:54-58", "Documented", "", "", "", "", ""),

    # ── Browser ──────────────────────────────────────────────────────────
    ("BRW-01", "Browser", "Screen entry layout",
     "As a user, I want to open the Metadata Browser so that I inspect/manage Impala tables",
     "Split layout: schema/filter inputs (aa_enc/*), table list, detail panel, Back/Describe/Drop bar",
     "browser.py:BrowserScreen.compose", "Documented", "", "", "", "", ""),
    ("BRW-02", "Browser", "Auto-load on open",
     "As a user, I want tables loaded on entry so that I avoid an extra keystroke",
     "auto_load default runs action_show_tables(); first table auto-described when non-empty",
     "browser.py:BrowserScreen.on_mount", "Documented", "", "", "", "", ""),
    ("BRW-03", "Browser", "Keyboard navigation",
     "As a user, I want shortcuts for Browse so that I work efficiently over SSH",
     "B/Esc back, Enter describe, D drop, S load tables, J/K move when list focused",
     "browser.py:BrowserScreen.BINDINGS", "Documented", "", "", "", "", ""),
    ("BRW-04", "Browser", "Load tables",
     "As a user, I want to list tables matching a filter so that I find dispatch tables",
     "S runs SHOW TABLES IN schema LIKE filter; loading text then rows; failure shows error + toast",
     "browser.py:BrowserScreen.action_show_tables", "Documented", "", "", "", "", ""),
    ("BRW-05", "Browser", "Empty table list",
     "As a user, I want clear feedback when none match so that I know the filter is empty",
     "Zero tables: row '(no tables)'; detail resets placeholder; Describe/Drop disabled",
     "browser.py:BrowserScreen.action_show_tables", "Documented", "", "", "", "", ""),
    ("BRW-06", "Browser", "Table selection gating",
     "As a user, I want Describe/Drop only on a real table so that I cannot act on placeholders",
     "Describe/Drop disabled with no/placeholder selection; enabled on a table row; refresh on highlight",
     "browser.py:BrowserScreen._update_action_state", "Documented", "", "", "", "", ""),
    ("BRW-07", "Browser", "Describe table",
     "As a user, I want to view a schema so that I know columns and types",
     "Enter/Describe runs DESCRIBE full_table; loading then Column/Type/Comment grid; meta line",
     "browser.py:BrowserScreen.action_describe", "Documented", "", "", "", "", ""),
    ("BRW-08", "Browser", "Fully qualified name",
     "As a user, I want short names resolved against schema so that DESCRIBE/DROP target right object",
     "Name with '.' used as-is; else qualified as schema.name using trimmed schema",
     "browser.py:BrowserScreen._full_table", "Documented", "", "", "", "", ""),
    ("BRW-09", "Browser", "Describe error display",
     "As a user, I want DESCRIBE failures shown so that I diagnose without leaving Browse",
     "On exception, error text shown in detail body; title still shows attempted name",
     "browser.py:BrowserScreen.action_describe", "Documented", "", "", "", "", ""),
    ("BRW-10", "Browser", "Auto-describe after load",
     "As a user, I want first table auto-described so that I immediately see schema",
     "After load with >=1 table, cursor to row 0 and Describe runs",
     "browser.py:BrowserScreen.action_show_tables", "Documented", "", "", "", "", ""),
    ("BRW-11", "Browser", "Drop confirmation",
     "As a user, I want typed confirmation before DROP so that accidental deletes are prevented",
     "Drop opens danger modal 'DROP TABLE'; must type exact full name; Confirm 'Drop'/cancel 'Keep Table'",
     "browser.py:BrowserScreen._confirm_drop", "Documented", "", "", "", "", ""),
    ("BRW-12", "Browser", "Drop cancel",
     "As a user, I want to cancel a DROP safely so that the table is kept",
     "Cancel/N/Esc or wrong text returns False; no Impala call; UI unchanged",
     "browser.py:BrowserScreen._drop_flow", "Documented", "", "", "", "", ""),
    ("BRW-13", "Browser", "Drop success",
     "As a user, I want successful DROP to refresh so that UI matches Impala",
     "Confirmed success: toast 'Dropped {full}'; list reloads (no auto-describe); detail success msg",
     "browser.py:BrowserScreen._drop_flow", "Documented", "", "", "", "", ""),
    ("BRW-14", "Browser", "Drop failure",
     "As a user, I want DROP errors surfaced so that I know it was not removed",
     "On exception: detail error (red); toast 'DROP failed: {msg}'; list not refreshed",
     "browser.py:BrowserScreen._drop_flow", "Documented", "", "", "", "", ""),
    ("BRW-15", "Browser", "Initial placeholder",
     "As a user, I want guidance before selecting so that I know how to use the screen",
     "Before selection: title 'No table selected'; body 'Select a table and press Enter...'",
     "browser.py:BrowserScreen._show_detail_placeholder", "Documented", "", "", "", "", ""),
    ("BRW-16", "Browser", "Back navigation",
     "As a user, I want to leave Browse without side effects so that I return",
     "Back or B/Esc calls app.pop_screen() with no Impala calls",
     "browser.py:BrowserScreen.on_button_pressed", "Documented", "", "", "", "", ""),

    # ── Impala service ───────────────────────────────────────────────────
    ("IMP-01", "Impala", "Shell invocation",
     "As a user, I want metadata queries via production impala-shell so that results match cluster",
     "Metadata SQL runs impala-shell -k -i ... --ssl --delimited --print_header -q with 30s timeout",
     "impala.py:IMPALA_BASE_ARGV", "Documented", "", "", "", "", ""),
    ("IMP-02", "Impala", "Query errors",
     "As a user, I want shell failures as readable errors so that Browse can show them",
     "Non-zero exit raises RuntimeError from stderr/stdout/'impala-shell exited {rc}'",
     "impala.py:query", "Documented", "", "", "", "", ""),
    ("IMP-03", "Impala", "SHOW TABLES parsing",
     "As a user, I want a clean table list so that the UI is not cluttered",
     "show_tables returns non-empty stripped lines; lines starting 'Mock ' excluded",
     "impala.py:show_tables", "Documented", "", "", "", "", ""),
    ("IMP-04", "Impala", "DESCRIBE",
     "As a user, I want pipe-delimited DESCRIBE so that Browser renders a grid",
     "describe_table runs DESCRIBE {full}; returns raw stdout for parsing",
     "impala.py:describe_table", "Documented", "", "", "", "", ""),
    ("IMP-05", "Impala", "DROP TABLE idempotent",
     "As a user, I want idempotent DROP so that dropping a missing table does not hard-fail",
     "drop_table runs DROP TABLE IF EXISTS {full}; returns stdout on success",
     "impala.py:drop_table", "Documented", "", "", "", "", ""),
    ("IMP-06", "Impala", "Query timeout",
     "As a user, I want hung shell calls terminated so that Browse does not freeze",
     "communicate limited to 30s; on timeout process terminated and TimeoutError propagates",
     "impala.py:query", "Documented", "", "", "", "", ""),

    # ── Kerberos service ─────────────────────────────────────────────────
    ("KRB-01", "Kerberos", "Ticket presence check",
     "As a user, I want ticket presence detected so that preflight blocks unauthenticated runs",
     "has_ticket runs klist -s (5s); True iff exit 0; missing klist logs warning, returns False",
     "kerberos.py:has_ticket", "Documented", "", "", "", "", ""),
    ("KRB-02", "Kerberos", "Ticket TTL read",
     "As a user, I want remaining lifetime so that UI warns before expiry",
     "ticket_ttl_seconds runs klist (5s); rc!=0/missing returns None; else parses first expiry",
     "kerberos.py:ticket_ttl_seconds", "Documented", "", "", "", "", ""),
    ("KRB-03", "Kerberos", "TTL parsing format",
     "As a user, I want TTL from standard klist timestamps so that it matches corporate tooling",
     "Parser scans >=4 field lines; expiry MM/DD/YYYY HH:MM:SS; returns max(0,int(seconds))",
     "kerberos.py:parse_ttl_seconds", "Documented", "", "", "", "", ""),
    ("KRB-04", "Kerberos", "Expired ticket TTL",
     "As a user, I want expired tickets as zero so that sub-threshold checks fire",
     "Past expiry clamps TTL to 0 (not negative)",
     "kerberos.py:parse_ttl_seconds", "Documented", "", "", "", "", ""),
    ("KRB-05", "Kerberos", "Missing client graceful",
     "As a user, I want graceful behavior when klist absent so that the TUI does not crash",
     "FileNotFoundError/OSError -> has_ticket False, ttl None, warning logged",
     "kerberos.py:ticket_ttl_seconds", "Documented", "", "", "", "", ""),

    # ── Jobs service ─────────────────────────────────────────────────────
    ("JOBS-01", "Jobs", "Manifest listing",
     "As a user, I want jobs listed from disk so that supervision survives restarts",
     "list_manifests reads jobs_dir/*/manifest.json newest-first; missing dir []; corrupt skipped",
     "jobs.py:list_manifests", "Documented", "", "", "", "", ""),
    ("JOBS-02", "Jobs", "Running job count",
     "As a user, I want Running jobs identified so that the cap can be enforced",
     "running_jobs filters manifests where state == Running",
     "jobs.py:running_jobs", "Documented", "", "", "", "", ""),
    ("JOBS-03", "Jobs", "Running cap",
     "As a user, I want at most two Running so that cluster load is bounded",
     "can_launch True only when len(running_jobs()) < RUNNING_CAP (2)",
     "jobs.py:can_launch", "Documented", "", "", "", "", ""),
    ("JOBS-04", "Jobs", "Active jobs window",
     "As a user, I want recent finished jobs on dashboard so that I monitor outcomes",
     "active_jobs includes Running, no finished_at, or finished within 7 days",
     "jobs.py:active_jobs", "Documented", "", "", "", "", ""),
    ("JOBS-05", "Jobs", "History split",
     "As a user, I want >7-day jobs separated so that dashboard stays focused",
     "history_jobs includes only finished_at set and finished >7 days ago",
     "jobs.py:history_jobs", "Documented", "", "", "", "", ""),
    ("JOBS-06", "Jobs", "Manifest cache",
     "As a user, I want fast repeated refreshes so that polling does not re-read unchanged files",
     "Manifests cached by mtime; stale entries for deleted dirs purged on listing",
     "jobs.py:_load_manifest_cached", "Documented", "", "", "", "", ""),
    ("JOBS-07", "Jobs", "Timestamp parsing",
     "As a user, I want consistent UTC times so that the 7-day split is correct",
     "parse_time parses %Y-%m-%dT%H:%M:%SZ to UTC; None input returns None",
     "jobs.py:parse_time", "Documented", "", "", "", "", ""),

    # ── Manifest service ─────────────────────────────────────────────────
    ("MAN-01", "Manifest", "Job creation",
     "As a user, I want a job written at launch so that the detached runner picks it up",
     "create_job makes jobs_dir/{id}/ with job.sql, writes Pending manifest, returns dir+manifest",
     "manifest.py:create_job", "Documented", "", "", "", "", ""),
    ("MAN-02", "Manifest", "Job ID",
     "As a user, I want unique IDs so that manifests never collide",
     "ID format {UTC timestamp}_{6-char base32 token}",
     "manifest.py:new_job_id", "Documented", "", "", "", "", ""),
    ("MAN-03", "Manifest", "Legal source/destination",
     "As a user, I want illegal combinations rejected so that unsupported pipelines never start",
     "Only LEGAL_CELLS validate (SqlFile->all, SqlTemplate->Table, ExistingTable->Csv); else ValueError",
     "manifest.py:LEGAL_CELLS", "Documented", "", "", "", "", ""),
    ("MAN-04", "Manifest", "Atomic manifest write",
     "As a user, I want crash-safe updates so that supervision never reads half-written JSON",
     "write validates, writes .tmp, then atomically replaces manifest.json",
     "manifest.py:write", "Documented", "", "", "", "", ""),
    ("MAN-05", "Manifest", "SqlFile table materialization",
     "As a user, I want SELECT-to-table jobs to create tables so that Impala materializes output",
     "SqlFile->Table/Table+Csv wraps non-DDL SQL with table DDL; self-contained DDL verbatim",
     "manifest.py:_effective_job_sql", "Documented", "", "", "", "", ""),
    ("MAN-06", "Manifest", "Table+Csv decomposition",
     "As a user, I want table-then-CSV split into two steps so that each step uses right script",
     "build_orchestrator_calls appends Query_Impala_Parametrized.py then download_to_csv.py",
     "manifest.py:build_orchestrator_calls", "Documented", "", "", "", "", ""),
    ("MAN-07", "Manifest", "CSV output path",
     "As a user, I want CSV in launch CWD by default so that outputs are easy to find",
     "Default csv_path is launch_cwd/{table_name or dispatch_export}.csv",
     "manifest.py:build_orchestrator_calls", "Documented", "", "", "", "", ""),
    ("MAN-08", "Manifest", "Orchestrator argv resolution",
     "As a user, I want scr scripts invoked correctly so that jobs run without manual paths",
     "Scripts from DISPATCH_SCR_DIR or /ads_storage/dispatch/scr; exec+shebang or python3.x fallback",
     "manifest.py:script_argv", "Documented", "", "", "", "", ""),
    ("MAN-09", "Manifest", "State field",
     "As a user, I want state stored in manifest so that the TUI reflects runner progress",
     "States Pending/Running/Succeeded/Failed/Cancelled; Pending at create; runner transitions",
     "manifest.py:JobState", "Documented", "", "", "", "", ""),

    # ── Runner ───────────────────────────────────────────────────────────
    ("RUN-01", "Runner", "Detached start",
     "As a user, I want jobs to survive SSH disconnect so that long Impala work continues",
     "TUI spawns nohup setsid python -m dispatch.runner --job-dir <dir> with detached stdio",
     "process.py:launch_runner", "Documented", "", "", "", "", ""),
    ("RUN-02", "Runner", "Pending-only execution",
     "As a user, I want a job not double-started so that only one runner owns a job",
     "run() proceeds only if manifest Pending; else exits code 4 without manifest update",
     "runner.py:run", "Documented", "", "", "", "", ""),
    ("RUN-03", "Runner", "Running transition",
     "As a user, I want Running recorded at start so that dashboard shows in-flight work",
     "On start writes run.pid, sets Running, started_at UTC, pid; opens run.log",
     "runner.py:run", "Documented", "", "", "", "", ""),
    ("RUN-04", "Runner", "Sequential orchestrators",
     "As a user, I want multi-step jobs in order so that Table+Csv completes table first",
     "Runner iterates orchestrator_calls sequentially; stops on first non-zero exit",
     "runner.py:run", "Documented", "", "", "", "", ""),
    ("RUN-05", "Runner", "Success terminal state",
     "As a user, I want successful jobs Succeeded so that I download results confidently",
     "All calls exit 0 -> Succeeded, exit_code 0, finished_at set",
     "runner.py:_set_terminal_state", "Documented", "", "", "", "", ""),
    ("RUN-06", "Runner", "Failure terminal state",
     "As a user, I want failed exits recorded so that I inspect logs",
     "Non-zero exit -> Failed, exit_code rc, finished_at; unhandled exception Failed exit -1",
     "runner.py:run", "Documented", "", "", "", "", ""),
    ("RUN-07", "Runner", "Cancel on SIGTERM",
     "As a user, I want cancellation to stop orchestrator and mark Cancelled so that partial work is visible",
     "SIGTERM handler sets Cancelled, SIGTERM to child, up to 10s then SIGKILL",
     "runner.py:_handle_sigterm", "Documented", "", "", "", "", ""),
    ("RUN-08", "Runner", "Corrupt manifest at start",
     "As a user, I want unreadable manifests to fail fast so that I know it did not run",
     "Load/validate failure writes manifest.error.json; runner returns exit code 3",
     "runner.py:run", "Documented", "", "", "", "", ""),

    # ── Process ──────────────────────────────────────────────────────────
    ("PROC-01", "Process", "Subprocess gateway",
     "As a user, I want commands behind one API so that timeouts/encoding are consistent",
     "run_exec captures stdout/stderr utf-8 replace, returns (rc,out,err); optional timeout terminates",
     "process.py:run_exec", "Documented", "", "", "", "", ""),
    ("PROC-02", "Process", "Interactive kinit",
     "As a user, I want interactive Kerberos renewal so that tickets refresh from the TUI",
     "run_interactive runs foreground subprocess to completion, returns exit code",
     "process.py:run_interactive", "Documented", "", "", "", "", ""),
    ("PROC-03", "Process", "Cancel process group",
     "As a user, I want cancel to signal the whole group so that child orchestrators stop",
     "cancel_process_group(pid) sends SIGTERM via killpg",
     "process.py:cancel_process_group", "Documented", "", "", "", "", ""),

    # ── Config ───────────────────────────────────────────────────────────
    ("CFG-01", "Config", "Data root resolution",
     "As a user, I want per-user job storage so that jobs are isolated on the edge node",
     "data_root uses DISPATCH_DATA_ROOT else /ads_storage/{USER}; current_user from $USER/getpass",
     "config.py:data_root", "Documented", "", "", "", "", ""),
    ("CFG-02", "Config", "Dispatch home layout",
     "As a user, I want a predictable .dispatch dir so that install and jobs share one root",
     "dispatch_home = data_root/.dispatch; jobs_dir = dispatch_home/jobs",
     "config.py:dispatch_home", "Documented", "", "", "", "", ""),
    ("CFG-03", "Config", "User config file",
     "As a user, I want persistent preferences so that form defaults survive sessions",
     "config_path = dispatch_home/config.json; read_form_defaults returns {} on missing/invalid",
     "config.py:read_form_defaults", "Documented", "", "", "", "", ""),
    ("CFG-04", "Config", "Installed version marker",
     "As a user, I want install version recorded so that the app detects stale deployments",
     "installed_version_path = dispatch_home/installed_version (read at startup for mismatch)",
     "config.py:installed_version_path", "Documented", "", "", "", "", ""),
]


def render(out_path: Path | None = None) -> Path:
    out_path = out_path or (Path(__file__).parent / "feature-user-stories.csv")
    with out_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(FIELDS)
        for row in ROWS:
            if len(row) != len(FIELDS):
                raise SystemExit(
                    f"Row {row[0]} has {len(row)} fields, expected {len(FIELDS)}"
                )
            writer.writerow(row)
    return out_path


if __name__ == "__main__":
    path = render()
    print(f"Wrote {len(ROWS)} rows to {path}")
