import { SCENES, SceneId } from "./timeline";

export type VoiceoverLine = {
  scene: SceneId;
  /** Composition frame at which the line starts, i.e. the scene's own start. */
  start: number;
  /** Path under `public/`, generated by `tools/generate-voiceover.mjs`. */
  file: string;
  text: string;
};

const TEXT: Partial<Record<SceneId, string>> = {
  disconnect:
    "Your query ran for forty minutes. Then your laptop slept, and the SSH session died with it.",
  loop: "Dispatch runs on the edge node itself. You SSH in, change into the directory holding your SQL files, and type dispatch. That directory becomes the destination for every CSV in the session.",
  job: "A job is one source and one destination. A SQL file can land in a table, a CSV, or both. A template only writes tables. An existing table only exports to CSV.",
  refusals:
    "It refuses before it wastes your time. Illegal source and destination pairs, missing Kerberos tickets, tickets with under five minutes left, and a third job when two are already running.",
  detached:
    "Every job gets a manifest on disk. A detached runner owns the script execution, so closing the TUI does not touch the job. Reopen it later and the job list rebuilds from the manifests.",
  beforeAfter:
    "Same production scripts underneath. Dispatch handles the parameters, the detachment, and the checks you would otherwise run from memory.",
  telemetry:
    "Usage lands in JSONL files on the node, never over the network, and DISPATCH_TELEMETRY=0 turns it off. Contributors get six mock scenarios, so no one needs Hadoop or Kerberos to develop against it.",
  gettingStarted:
    "One operator activates the shared runtime on the node. Each analyst runs onboard once, which repairs their config and drops a launcher into their path without touching pip. After that it is cd and dispatch.",
  outro: "Setup notes and the release workflow are in docs.",
};

/**
 * The narration, keyed to the scene it belongs to. Scene 2 is deliberately
 * silent — that is where the music comes in.
 */
export const VOICEOVER: VoiceoverLine[] = SCENES.flatMap((scene) => {
  const text = TEXT[scene.id];
  if (!text) {
    return [];
  }
  return [
    {
      scene: scene.id,
      start: scene.start,
      file: `voiceover/${scene.id}.mp3`,
      text,
    },
  ];
});
